# Generated by Django 6.0.3 on 2026-03-26 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[("hotel", "Hotel"), ("villa", "Villa"), ("studio", "Studio")],
                default="hotel",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
